// <auto-generated />
using System;
using GTR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GTR.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916065506_FixMatchPlayerKey")]
    partial class FixMatchPlayerKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GTR.Domain.Entities.ChuckerResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChuckerNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Winner")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "ChuckerNumber")
                        .IsUnique();

                    b.ToTable("ChuckerResults", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChuckerResult_Number", "\"ChuckerNumber\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("GTR.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinalisedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("MatchDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("MvpPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate")
                        .IsUnique();

                    b.HasIndex("MvpPlayerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GTR.Domain.Entities.MatchPlayer", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Team")
                        .HasColumnType("integer");

                    b.Property<int>("Tries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("GTR.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GTR.Domain.Entities.PlayerAvailability", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAvailabilities");
                });

            modelBuilder.Entity("GTR.Domain.Entities.ChuckerResult", b =>
                {
                    b.HasOne("GTR.Domain.Entities.Match", "Match")
                        .WithMany("ChuckerResults")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GTR.Domain.Entities.Match", b =>
                {
                    b.HasOne("GTR.Domain.Entities.Player", "MvpPlayer")
                        .WithMany()
                        .HasForeignKey("MvpPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MvpPlayer");
                });

            modelBuilder.Entity("GTR.Domain.Entities.MatchPlayer", b =>
                {
                    b.HasOne("GTR.Domain.Entities.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTR.Domain.Entities.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GTR.Domain.Entities.PlayerAvailability", b =>
                {
                    b.HasOne("GTR.Domain.Entities.Match", "Match")
                        .WithMany("PlayerAvailabilities")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTR.Domain.Entities.Player", "Player")
                        .WithMany("AvailabilityRecords")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GTR.Domain.Entities.Match", b =>
                {
                    b.Navigation("ChuckerResults");

                    b.Navigation("MatchPlayers");

                    b.Navigation("PlayerAvailabilities");
                });

            modelBuilder.Entity("GTR.Domain.Entities.Player", b =>
                {
                    b.Navigation("AvailabilityRecords");

                    b.Navigation("MatchPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
